name: mindfuldost_hub
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors: ^2.0.3
  shake: ^2.2.0
  http: ^1.2.0
  flutter_cache_manager: ^3.3.1
  api_cache_manager: ^1.0.1
  vibration: ^1.8.4
  syncfusion_flutter_sliders: ^24.2.6



  # api_cache_manager: ^0.4.0   # Replace with the latest version
  # cache_db_model: ^0.4.0    

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logof.png
    - assets/images/screen1/logomarkscreen1.png
    - assets/images/loadingscreen2/vector-1.png
    - assets/images/loadingscreen2/vector-2.png
    - assets/images/loadingscreen2/vector-3.png
    - assets/images/loadingscreen2/Solid mobile.png
    - assets/images/loading screen3/frame1.png
    - assets/images/loading screen3/frame2.png
    - assets/images/welcome screen1/wsgrp1.png
    - assets/images/login-signup/logo.png
    - assets/images/welcome screen1/wsgrp2.png
    - assets/images/welcome screen1/wsgrp3.png